from odoo import models, fields, api


class SkipcashTransaction(models.Model):
    _name = "skipcash.transaction"
    _description = "Skipcash Transaction"

    amount = fields.Float(
        string="Transaction Amount",
        help="The total amount paid through Skipcash for this transaction."
    )
    payment_url = fields.Char(
        string="Payment URL",
        help="The URL generated by Skipcash for completing the payment."
    )
    payment_status = fields.Char(
        string="Payment Status",
        help="The current status of the payment (e.g., pending, successful, failed)."
    )
    payment_id = fields.Char(
        string="Payment ID",
        help="Unique identifier assigned by Skipcash for this payment."
    )
    vis_id = fields.Char(
        string="Visa ID",
        help="Reference identifier returned by Visa or Skipcash for tracking purposes."
    )
    voucher_purchase_id = fields.Many2one(
        "voucher.purchased.user",
        string="Voucher Purchase",
        help="The voucher purchase record linked to this Skipcash transaction."
    )

    @api.depends("payment_id", "payment_status")
    def _compute_display_name(self):
        for rec in self:
            rec.display_name = f"{rec.payment_id or 'No Payment ID'} - {rec.payment_status or 'Unknown'}"
