# noinspection PyStatementEffect
{
    "name": "Loyalty System",
    "version": "18.0.0.0.0",
    "category": "Tools",
    "summary": "Comprehensive Loyalty Management for Customers and Rewards.",
    "author": "Dhiren Narola",
    "license": "OPL-1",
    "depends": [
        "base",
        "product",
        "account",
        "mail",
        "uom",
    ],
    "data": [
        "data/data.xml",
        "security/ir.model.access.csv",
        "views/res_partner.xml",
        "views/loyalty_restaurant_order.xml",
        "views/loyalty_restaurant_category.xml",
        "views/user_address.xml",
        "views/loyalty_point_generator.xml",
        "views/loyalty_point_transfer.xml",
        "views/loyalty_rule.xml",
        "views/loyalty_sale.xml",
        "views/loyalty_notification.xml",
        "views/loyalty_notification_message.xml",
        "views/loyalty_contact_us.xml",
        "views/loyalty_notification_list.xml",
        "views/merchant_enquiry.xml",
        "views/menus.xml"
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
}
