# noinspection PyStatementEffect
{
    "name": "Loyalty System",
    "version": "18.0.0.0.0",
    "category": "Tools",
    "summary": "Comprehensive Loyalty Management for Customers and Rewards.",
    "author": "Dhiren Narola",
    "license": "OPL-1",
    "depends": [
        "base",
        "product",
        "account",
        "mail",
        "uom",
        "auth_signup",
        "go_sms"
    ],
    "data": [
        "data/data.xml",
        "data/mail_template.xml",
        "security/ir.model.access.csv",
        "views/res_partner.xml",
        "views/loyalty_restaurant_order.xml",
        "views/loyalty_restaurant_category.xml",
        "views/user_address.xml",
        "views/loyalty_point_generator.xml",
        "views/loyalty_point_transfer.xml",
        "views/loyalty_rule.xml",
        "views/loyalty_sale.xml",
        "views/loyalty_notification.xml",
        "views/loyalty_notification_message.xml",
        "views/loyalty_contact_us.xml",
        "views/loyalty_notification_list.xml",
        "views/merchant_enquiry.xml",
        "views/track_list.xml",
        "views/advertisement_tracking.xml",
        "views/merchant_branch.xml",
        "views/contract_matrix.xml",
        "views/notin_app.xml",
        "views/terms_matrix.xml",
        "views/loyalty_point_transfer_line.xml",
        "views/partner_category.xml",
        "views/res_company.xml",
        "views/org_registration_code.xml",
        "views/offer_usages_history.xml",
        "views/merchant_matrix.xml",
        "views/merchant_banner.xml",
        "views/menus.xml"
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
}
