# noinspection PyStatementEffect
{
    "name": "Go Voucher",
    "version": "18.0.0.0.0",
    "category": "Tools",
    "sequence": 500,
    "summary": "Create, manage, and redeem discount vouchers with merchant and organisation support in Odoo.",
    "author": "Dhiren Narola",
    "license": "OPL-1",
    "depends": ["go_giftcard", "go_organization", "mail", "go_subscription"],
    "data": [
        "data/ir_cron_data.xml",
        "data/mail_template.xml",
        "security/ir.model.access.csv",
        "views/discount_voucher.xml",
        "views/skipcash_transaction.xml",
        "views/voucher_purchased_user.xml",
        "views/voucher_redeemed_user.xml",
        "views/voucher_saved_user.xml",
        "views/res_config_settings.xml",
        "views/menuitems.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
}
